language: node_js
node_js:
  - "12.10.0"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
    - NODE_ENV=test
    - DB_NAME=books
    - DB_USER=kevin
    - DB_PASS=kevin
    - DB_PORT=5432
    - SECRET_KEY=secret

before_script:
  - psql -c 'create database book_test;' -U postgres
  - psql -c "CREATE USER kevin WITH PASSWORD kevin;" -U postgres
  - npm run build
  - npm install -g sequelize-cli
  - sequelize db:migrate
script:
  - npm test
after_success:
  - npm run coverage
